import type { PostCategory } from "./types";
import { getSourcesByCategory, type RSSSource } from "./rss-sources";

export interface ParsedNewsItem {
  title: string;
  description: string;
  link: string;
  source: string;
  pubDate?: string;
}

// Parse RSS XML into structured items
export function parseRSSXml(xml: string, sourceName: string): ParsedNewsItem[] {
  const items: ParsedNewsItem[] = [];
  const itemRegex = /<item>([\s\S]*?)<\/item>/g;
  let match;

  while ((match = itemRegex.exec(xml)) !== null) {
    const itemXml = match[1];
    const title = extractTag(itemXml, "title");
    const description = extractTag(itemXml, "description");
    const link = extractTag(itemXml, "link");
    const pubDate = extractTag(itemXml, "pubDate");

    if (title) {
      items.push({
        title: stripHtml(title),
        description: stripHtml(description || ""),
        link: link || "",
        source: sourceName,
        pubDate: pubDate || undefined,
      });
    }
  }

  return items.slice(0, 5); // Top 5 per source
}

function extractTag(xml: string, tag: string): string | null {
  const cdataMatch = xml.match(new RegExp(`<${tag}><!\\[CDATA\\[([\\s\\S]*?)\\]\\]></${tag}>`));
  if (cdataMatch) return cdataMatch[1];
  const simpleMatch = xml.match(new RegExp(`<${tag}>(.*?)</${tag}>`, "s"));
  return simpleMatch ? simpleMatch[1] : null;
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').trim();
}

// Fetch news from RSS feeds for a given category
export async function fetchNewsForCategory(category: PostCategory): Promise<ParsedNewsItem[]> {
  const sources = getSourcesByCategory(category);
  const allItems: ParsedNewsItem[] = [];

  for (const source of sources) {
    try {
      const response = await fetch(source.url, {
        headers: { "User-Agent": "LoktantraVani/1.0 NewsAgent" },
        next: { revalidate: 3600 },
      });
      if (response.ok) {
        const xml = await response.text();
        const items = parseRSSXml(xml, source.name);
        allItems.push(...items);
      }
    } catch (error) {
      console.warn(`Failed to fetch RSS from ${source.name}:`, error);
    }
  }

  return allItems;
}

// Generate a LoktantraVani-style article from news items
export function generateArticleDraft(
  topic: string,
  category: PostCategory,
  newsItems: ParsedNewsItem[]
): {
  title: string;
  titleHi: string;
  summary: string;
  content: string;
  sources: string[];
} {
  // Compose article from collected news items
  const sourceNames = [...new Set(newsItems.map((n) => n.source))];
  const topItems = newsItems.slice(0, 5);

  const title = `${topic}: A Neo Bharat Analysis`;
  const titleHi = `${topic}: एक नव भारत विश्लेषण`;

  const summary = `An AI-curated analysis of recent developments in ${topic}, compiled from ${sourceNames.join(", ")} through the LoktantraVani editorial lens.`;

  let content = `<p class="text-xl font-newsreader italic mb-8">This article was generated by the LoktantraVani News Agent, drawing from ${newsItems.length} recent reports across ${sourceNames.length} sources.</p>\n\n`;

  content += `<h2>Key Developments</h2>\n`;
  for (const item of topItems) {
    content += `<p><strong>${item.title}</strong> — ${item.description}</p>\n`;
    content += `<p class="text-xs opacity-50">Source: ${item.source}</p>\n`;
  }

  content += `\n<h2>The Neo Bharat Perspective</h2>\n`;
  content += `<p>From a civilizational standpoint, these developments in ${category.toLowerCase()} reflect the ongoing realignment of global power structures. India's position — rooted in strategic autonomy and dharmic principles — offers a unique vantage point for understanding these shifts.</p>\n`;

  content += `\n<blockquote>This article was generated by the LoktantraVani AI News Agent and requires editorial review before publication.</blockquote>\n`;

  return {
    title,
    titleHi,
    summary,
    content,
    sources: topItems.map((i) => i.link).filter(Boolean),
  };
}
